version: '1'
services:
  mysql-server:
    image: 'mysql/mysql-server:8.0'
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d
  python-client:
    image: laudio/pyodbc:1.0.37-sqlcmd
    command: tail -F anything
  sqoop-client:
    image: dvoros/sqoop:hive2-sqoop1.4.7
    volumes:
      - ./jdbc_drivers:/jdbc
    command: bash -c "cp /jdbc/* /usr/local/sqoop/lib && /etc/bootstrap.sh && hdfs dfsadmin -safemode leave && tail -F anything"
  pyspark-client:
    image: jupyter/pyspark-notebook
    volumes:
      - ./jdbc_drivers:/jdbc